### PR TITLE
WIP: Implement mssql base counters

### LINKED ISSUE #250: sql collector : strange values for bufman_buffer_cache_hit_ratio
Hi,

While trying to set up a dashboard for a MS SQL, I have come upon  wmi_mssql_bufman_buffer_cache_hit_ratio which sometimes has values over 100.

I'm not very familiar with MSSQL, so I was wondering wether this is expected behaviour or if something is wrong ?

I'm using wmi_exporter 0.4.3 on windows 2016 and sql server express 13.0.4001.0.

### PR DESCRIPTION
**Pull request by secustor**
Resolves #250

Continuation of https://github.com/martinlindhe/wmi_exporter/pull/352 as this contribution seems to be abandoned.

### CODE REVIEW

File: collector/mssql.go [hunk 1]
```diff
@@ -137,49 +137,50 @@ type MSSQLCollector struct {
...
+	AccessMethodsRangeScans                    *prometheus.Desc
+	AccessMethodsScanPointRevalidations        *prometheus.Desc
+	AccessMethodsSkippedGhostedRecords         *prometheus.Desc
+	AccessMethodsTableLockEscalations          *prometheus.Desc
+	AccessMethodsUsedleafpagecookie            *prometheus.Desc
+	AccessMethodsUsedtreepagecookie            *prometheus.Desc
+	AccessMethodsWorkfilesCreated              *prometheus.Desc
+	AccessMethodsWorktablesCreated             *prometheus.Desc
+	AccessMethodsWorktablesFromCacheRatio      *prometheus.Desc
+	AccessMethodsWorktablesFromCacheRatio_Base *prometheus.Desc
```
Comment (carlpett) [inline collector/mssql.go]: It would be nice to not leak the counter-internal names into our "clean" structs, but rather have the names here reflect what they mean. So something like `AccessMethodsWorktablesFromCacheLookups`?
(This goes for all the new fields added below as well)

File: collector/mssql.go [hunk 2]
```diff
@@ -662,6 +666,12 @@ func NewMSSQLCollector() (Collector, error) {
 			[]string{"instance"},
 			nil,
 		),
+		AccessMethodsWorktablesFromCacheRatio_Base: prometheus.NewDesc(
+			prometheus.BuildFQName(Namespace, subsystem, "accessmethods_worktables_from_cache_ratio_lookups"),
```
Comment (carlpett) [inline collector/mssql.go]: Skip the `_ratio` here, since it is not lookups on the ratio

Comment (carlpett) [reply collector/mssql.go]: Also, the metric `accessmethods_worktables_from_cache_ratio` should probably be `accessmethods_worktables_from_cache_hits`, right?

Comment (carlpett) [reply collector/mssql.go]: _(The above seems to repeat for all the new changes)_

File: collector/mssql.go [hunk 3]
```diff
@@ -1430,6 +1452,12 @@ func NewMSSQLCollector() (Collector, error) {
 			[]string{"instance", "resource"},
 			nil,
 		),
+		LocksAverageWaitTimems_Base: prometheus.NewDesc(
+			prometheus.BuildFQName(Namespace, subsystem, "locks_average_wait_seconds_lookups"),
```
Comment (carlpett) [inline collector/mssql.go]: This isn't clear to me - what does this mean?

File: docs/collector.mssql.md [hunk 4]
```diff
@@ -249,7 +253,16 @@ Name | Description | Type | Labels
 _This collector does not yet have explained examples, we would appreciate your help adding them!_
 
 ## Useful queries
-_This collector does not yet have any useful queries added, we would appreciate your help adding them!_
+
+### Buffer Cache Hit Ratio
+
+When you read the counter in perfmon you will get the the percentage pages found in the buffer cache. This percentage is calculated internally based on the total number of cache hits divided by the total number of cache lookups over the last few thousand page accesses.
+This collector retrieves the two internal values separately. In order to give any meaning to the value you will have to calculate the Buffer Cache Hit Ratio in PromQL.
```
Comment (carlpett) [inline docs/collector.mssql.md]: This is a bit strongly formulated - the values *do* have meaning separately. Just not the hit ratio, which the current naming implies. So with improved naming in the PR, I think this will be less confusing.
The example query is still good to have here, though!

File: collector/mssql.go (hunk 2 above)
Comment (secustor) [reply collector/mssql.go]: The bases have no meaning on itself if you go by the Microsoft documentation.    
Better said MS is not sharing  what they are in their [documentation](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-buffer-manager-object?view=sql-server-ver15).    
Because of this I would prefer the naming style of @sqlkabouter .

We can't be sure here as we have to go with the documentation of Microsoft.

File: collector/mssql.go (hunk 3 above)
Comment (secustor) [reply collector/mssql.go]: As there is no description in the MS [documentation](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-locks-object?view=sqlallproducts-allversions) I can only guess that this is are the number of lock events.

File: collector/mssql.go (hunk 2 above)
Comment (carlpett) [reply collector/mssql.go]: I'm sorry to be a bit contrarian here, but while I appreciate that the documentation is a bit vague and the current naming wrong, I'm not sure I'm keen on merging something which introduces _more_ unclarity. The name here is pretty bad in that regard, in my opinion.
Looking at the docs you linked:
>The ratio is the total number of cache hits divided by the total number of cache lookups over the last few thousand page accesses.

By that definition, it seems pretty clear to me that we get the total lookups in the base, and total hits in the "non-base" counter? Are there other reasonable interpretations I'm missing?

File: collector/mssql.go (hunk 3 above)
Comment (carlpett) [reply collector/mssql.go]: Ok, so then we'd have `lock_wait_seconds_total` and `lock_waited_total` or something similar in naming?

File: collector/mssql.go (hunk 2 above)
Comment (secustor) [reply collector/mssql.go]: It seems to be the case after testing with MS monitoring tools.    
Our DB team will hopefully confirm with this Snapshot that the results using Prometheus+WMI_Exporter and MS tools report the same stats.

**Comment by secustor** [comment]
@carlpett Can give me feedback what is not working in the pipeline?    
It seems like I have no access to the logs.

**Comment by carlpett** [comment]
@secustor It seems it didn't even try to build... And Github's usability team could do better here I think - I need to hover over the failing check to get the text "AppVeyor was unable to build non-mergeable pull request". So if you resolve the conflict it will build.

**Comment by carlpett** [comment]
I hope you can see the build logs this time? If not, the failing part is linting, specifically that the files are not `gofmt`:ed.

File: collector/mssql.go [hunk 5]
```diff
@@ -1054,9 +1070,15 @@ func NewMSSQLCollector() (Collector, error) {
...
-			prometheus.BuildFQName(Namespace, subsystem, "databases_log_cache_hit_ratio"),
-			"(Databases.LogCacheHitRatio)",
+		DatabasesLogCacheHits: prometheus.NewDesc(
+			prometheus.BuildFQName(Namespace, subsystem, "databases_log_cache_hits"),
+			"(Databases.LogCacheHits)",
+			[]string{"instance", "database"},
+			nil,
+		),
+		DatabasesLogCacheLookups: prometheus.NewDesc(
+			prometheus.BuildFQName(Namespace, subsystem, "databases_log_cache_hit_lookups"),
```
Comment (carlpett) [inline collector/mssql.go]: Typo?
```suggestion
			prometheus.BuildFQName(Namespace, subsystem, "databases_log_cache_lookups"),
```

File: collector/mssql.go [hunk 6]
```diff
@@ -1862,7 +1890,8 @@ type win32PerfRawDataSQLServerAccessMethods struct {
 	Usedtreepagecookie            uint64
 	WorkfilesCreatedPersec        uint64
 	WorktablesCreatedPersec       uint64
-	WorktablesFromCacheRatio      uint64
+	WorktablesFromCacheHits       uint64
+	WorktablesFromCacheLookups    uint64
```
Comment (carlpett) [inline collector/mssql.go]: Is this a find/replace mistake? The underlying counters are `WorktablesFromCacheRatio` and `WorktablesFromCacheRatio_Base`, right?

File: collector/mssql.go [hunk 7]
```diff
@@ -2281,7 +2317,8 @@ func (c *MSSQLCollector) collectAvailabilityReplica(ch chan<- prometheus.Metric,
 //   https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-buffer-manager-object
 type win32PerfRawDataSQLServerBufferManager struct {
 	BackgroundwriterpagesPersec   uint64
-	Buffercachehitratio           uint64
+	Buffercachehits               uint64
+	Buffercachelookups            uint64
```
Comment (carlpett) [inline collector/mssql.go]: Same here, the field names need to match the WMI counter names

File: collector/mssql.go [hunk 8]
```diff
@@ -2703,7 +2747,8 @@ type win32PerfRawDataSQLServerDatabases struct {
 	DBCCLogicalScanBytesPersec       uint64
 	GroupCommitTimePersec            uint64
 	LogBytesFlushedPersec            uint64
-	LogCacheHitRatio                 uint64
+	LogCacheHits                     uint64
+	LogCacheLookups                  uint64
```
Comment (carlpett) [inline collector/mssql.go]: One more

File: collector/mssql.go [hunk 9]
```diff
@@ -3298,7 +3350,8 @@ func (c *MSSQLCollector) collectGeneralStatistics(ch chan<- prometheus.Metric, s
 // - https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-locks-object
 type win32PerfRawDataSQLServerLocks struct {
 	Name                       string
-	AverageWaitTimems          uint64
+	LockWaitTime               uint64
+	LockCount                  uint64
```
Comment (carlpett) [inline collector/mssql.go]: And the last one

File: collector/mssql.go (hunk 6 above)
Comment (secustor) [reply collector/mssql.go]: You are correct

File: collector/mssql.go (hunk 5 above)
Comment (secustor) [reply collector/mssql.go]: Yes this is a typo

**Comment by carlpett** [comment]
Thank you so very much @secustor! :clap:
